# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.17.1
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: false
github_enable_stale_action: true
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: OCB
odoo_version: 12.0
org_name: Quartile Limited
org_slug: qrtl
rebel_module_groups: []
repo_description: null
repo_name: ASX Custom
repo_slug: asx-custom
repo_website: https://www.quartile.co
travis_apt_packages: []
travis_apt_sources: []

